language: php


php:
    - 5.6

install:
 - composer self-update
 - composer install

#before_script: chmod +x ./codeclimate.sh

script: phpunit --configuration phpunit.xml

#after_script: ./codeclimate.sh